name: Sync to arojaspa Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HG: ${{ secrets.HG }}
        run: git remote add space https://arojaspa:$HG@huggingface.co/spaces/arojaspa/huggingface-demo1
      - name: Push to hub
        env:
          HG: ${{ secrets.HG }}
        run: git push --force https://arojaspa:$HG@huggingface.co/spaces/arojaspa/huggingface-demo1 main
