name: Sync to arojaspa Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Installing packages
        run: make install

      - name: Add git remote
        env:
          HF_TOKEN: ${{ secrets.HG }}
        run: git remote add space https://arojaspa:$HF_TOKEN@huggingface.co/spaces/arojaspa/huggingface-demo1
          
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HG }}
        run: git push --force https://arojaspa:$HF_TOKEN@huggingface.co/spaces/arojaspa/huggingface-demo1 main
